### ISSUE TITLE
Error loading the weights

### ISSUE THREAD

**Issue by Abokhatwa** [Yukichiii/Swin3D_Task#7]
Hi,

Whenever I try to load the weights into the model, I get the following error:
![image](https://github.com/user-attachments/assets/fd87f41a-3c2e-477e-b28d-2569f8f21836)

is there any solution to this error ?

**Comment by Yukichiii** [comment]
It seems that there's no error here. This is the setting for not loading the pretrained decoder in the finetune stage.
